added mapname.lua
qbcore-framework/qb-smallresources pull request #154
Opened 2022-01-05 09:54 UTC by iboss21

small config to rename the map when you click the P or ESC button

2022-01-05 18:42 UTC, amantu-qbit approved these changes

2022-01-05 18:44 UTC, amantu-qbit reviewed
Change:
Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
to:
InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)

2022-01-05 18:56 UTC, izMystic commented
All you need is this
```lua
CreateThread(function()
  AddTextEntry('FE_THDR_GTA0', 'Text You Want')
end)
```

2022-01-05 19:32 UTC, iboss21 commented
> All you need is this
> 
> ```lua
> CreateThread(function()
>   AddTextEntry('FE_THDR_GTA0', 'Text You Want')
> end)
> ```
> 
> Don't need a function invoking a native when that's already a native

that's amazing then. thank you izMystic

2022-08-26 17:37 UTC, dexter9006 requested changes

2022-08-26 17:37 UTC, dexter9006 commented on client/mapname.lua
> +
as said, you only need the 3 lignes below

2022-08-26 19:45 UTC, iboss21 commented
Got it thanks


On Fri, Aug 26, 2022 at 1:38 PM dexter9006 ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In client/mapname.lua
> <https://github.com/qbcore-framework/qb-smallresources/pull/154#discussion_r956262116>
> :
>
> > @@ -0,0 +1,11 @@
> +-- mapname
> +-- github https://github.com/iboss21
> +-- Discord iBoss#2984
> +
> +function AddTextEntry(key, value)
> +	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
> +end
> +
>
> as said, you only need the 3 lignes below
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/qbcore-framework/qb-smallresources/pull/154#pullrequestreview-1087312586>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALPWDC344ORZ4TOGNIWUWHDV3D6HXANCNFSM5LJPR32Q>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-09 16:09 UTC, Z3rio requested changes
Remove unneeded stuff

2022-12-09 16:09 UTC, Z3rio commented on client/mapname.lua
> +
```suggestion
```
Remove self promotion

2022-12-09 16:09 UTC, Z3rio commented on client/mapname.lua
> +
Unneeded function, since it's anyways only used once.

2022-12-09 16:09 UTC, Z3rio commented on client/mapname.lua
> +  AddTextEntry('FE_THDR_GTAO', '~y~ The Name | ~b~ OF Your Server, ~s~ RP..')
```suggestion
  Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), "FE_THDR_GTAO", Config.MapText)
```

2022-12-09 16:11 UTC, Z3rio commented on client/mapname.lua
> +
```suggestion
```
Unneeded function

2022-12-09 16:13 UTC, Z3rio approved these changes

2022-12-09 16:13 UTC, merged