cron - do stuff in a specified time
qbcore-framework/qb-smallresources pull request #191
Opened 2022-02-17 17:41 UTC by darknight2590

```
-- Execute task 5:10, every day
function CronTask(d, h, m)
  print('Task done')
end

TriggerEvent('cron:runAt', 5, 10, CronTask)

-- Execute task every monday at 18:30
function CronTask(d, h, m)
  if d == 1 then
    print('Task done')
  end
end

TriggerEvent('cron:runAt', 18, 30, CronTask)
```

2022-02-20 11:43 UTC, mjvanhaastert reviewed
oh i like this functions

2022-12-09 17:03 UTC, Z3rio requested changes
Incredibly good feature, although with an incredibly large exploit.

2022-12-09 17:03 UTC, Z3rio commented on server/cron.lua
> +end)
This is incredibly insecure, you can trigger this from any cheat and inject any code you want (which would run on the serverside).
If you want this feature then an export shall be used.
```suggestion
exports("cronrunAt", function(h, m, cb)
	RunAt(h, m, cb)
end)
```

2022-12-09 18:15 UTC, Z3rio requested changes

2022-12-09 18:15 UTC, Z3rio commented on server/cron.lua
> +end)
```suggestion
-- Variables
local Jobs = {}

-- Functions
function GetTime()
	local timestamp = os.time()
	local day = tonumber(os.date('*t', timestamp).wday)
	local hour = tonumber(os.date('%H', timestamp))
	local min = tonumber(os.date('%M', timestamp))

	return {day = day, hour = hour, min = min}
end

function CheckTimes(day, hour, min)
	for i,v in pairs(Jobs) do
		if v.hour == hour and v.min == min then
			v.cb(day, hour, min)
		end
	end
end

-- Exports
exports("CreateCronJob", function(hour, min, cb)
	if hour and type(hour) == "number" and min and type(min) == "number" and cb and (type(cb) == "function" or type(cb) == "table") then
		table.insert(Jobs, {
			min  = min,
			hour  = hour,
			cb = cb
		})
	else
		print("WARN: Invalid arguments for cronrunAt(hour, min, cb)")
	end
end)

-- Main Loop
Citizen.CreateThread(function()
	while true do
		local time = GetTime()
		CheckTimes(time.day, time.hour, time.min)

		Citizen.Wait(60 * 1000)
	end
end)
```
Refactor code + patch exploitation

2022-12-09 18:36 UTC, Z3rio requested changes
Fix linting

2022-12-09 18:36 UTC, Z3rio commented on server/cron.lua
> +			v.cb(day, hour, min)
```suggestion
	for i = 1, #Jobs, 1 do
		local data = Jobs[i]
		if data.hour == hour and data.min == min then
			data.cb(day, hour, min)
```
Fix linting

2022-12-09 18:42 UTC, Z3rio approved these changes
LGTM, good PR

2022-12-09 18:42 UTC, merged