fix(hudcomponents): don't wait four frames
qbcore-framework/qb-smallresources pull request #249
Opened 2022-08-12 14:21 UTC by NotSomething0

Waiting even just one frame causes blinking which can be seen [here](https://i.imgur.com/KGXkhOX.mp4)

2022-08-12 14:41 UTC, BerkieBb requested changes

2022-08-12 14:41 UTC, BerkieBb commented on client/hudcomponents.lua
> +    for _, component in pairs(DISABLED_COMPONENTS) do
Use iterator instead
```lua
for i = 1, #DISABLED_COMPONENTS do
    HideHudComponentThisFrame(DISABLED_COMPONENTS[i]
end
```
This is faster than using pairs

2022-08-12 14:45 UTC, BerkieBb commented
Just so you know, Wait accepts milliseconds as an argument, not frames, frames are rather a sort of like part where code gets executed, the amount of time a frame takes relies on the performance of the system and the code it has to run, on higher end systems, frames can take less longer than lower end systems because they have more performance and can run everything faster

2022-08-12 14:57 UTC, NotSomething0 commented
Yeah usually they get used interchangeably when used in conversation thanks for the explanation though :)

2022-08-12 16:53 UTC, BerkieBb commented
One more thing btw, the indentation is at 2 spaces, can you please change it to 4 spaces?

2022-08-12 21:17 UTC, NotSomething0 commented
Should be good now

2022-08-19 18:18 UTC, BerkieBb commented
Added in #250

2022-08-19 18:18 UTC, closed without merging