Object Removal loop Removed
qbcore-framework/qb-smallresources pull request #275
Opened 2022-09-12 18:35 UTC by KamuiKody

The loop is not needed i added a polyzone instead of the distance check the object doesnt spawn back in until you are far from the area anyways.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

2022-09-17 07:56 UTC, r0adra93 approved these changes

2022-12-10 12:46 UTC, Z3rio requested changes

2022-12-10 12:46 UTC, Z3rio commented on client/removeentities.lua
> +
```suggestion
```
Remove extra whitespace

2022-12-10 13:28 UTC, Z3rio approved these changes
Works great upon testing ingame.

2022-12-10 13:30 UTC, merged