Reorganize the script
qbcore-framework/qb-smallresources pull request #94
Opened 2021-10-21 06:33 UTC by evanillaa

2021-10-21 15:16 UTC, Eralpozcan approved these changes

2021-10-31 19:06 UTC, GhzGarage commented
Conflicts

2021-10-31 19:35 UTC, Slay3rIQ requested changes
There is no carwash at:

    [4] = {
        ["label"] = "Hands Free Carwash",
        ["coords"] = vector3(-1200.4, -1720.46, 3.40),
    },

2021-10-31 19:41 UTC, evanillaa commented on server/consumables.lua
> +RegisterServerEvent("qb-smallpenis:server:AddParachute")
It is in the project by default
I did not modify it

2021-10-31 20:14 UTC, merged